# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jdavis <marvin@42.fr>                      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/01/20 14:58:17 by jdavis            #+#    #+#              #
#    Updated: 2022/01/21 11:20:48 by jdavis           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = test_fillit

ABSOL_PATH = ~/Desktop/fillit/fillit_project/

all: $(NAME)

$(NAME):
	make -C ../ fclean && make -C ../

valid_tests:
	../fillit valid/tetri1.txt
	../fillit valid/tetri2.txt
	../fillit valid/tetri3.txt
	../fillit valid/tetri4.txt
	../fillit valid/tetri5.txt
	../fillit valid/tetri6.txt
	../fillit valid/tetri7.txt
	../fillit valid/tetri8.txt
	../fillit valid/tetri9.txt
	../fillit valid/tetri10.txt
	../fillit valid/tetri11.txt
	../fillit valid/tetri12.txt
	../fillit valid/tetri13.txt
	../fillit valid/tetri14.txt
	../fillit valid/tetri15.txt
	../fillit valid/tetri16.txt
	../fillit valid/tetri17.txt
	../fillit valid/tetri18.txt
	../fillit valid/tetri19.txt
	../fillit valid/tetri20.txt
	../fillit valid/tetri21.txt
	../fillit valid/tetri23.txt
	../fillit valid/tetri25.txt
	../fillit valid/tetri26.txt
	../fillit valid/tetri27.txt
	../fillit valid/tetri22.txt
	../fillit valid/tetri28.txt

notval1:
	../fillit notvalid/tetri1.txt

notval2:
	../fillit notvalid/tetri2.txt
notval3:
	../fillit notvalid/tetri3.txt
notval4:
	../fillit notvalid/tetri4.txt
notval5:
	../fillit notvalid/tetri5.txt
notval6:
	../fillit notvalid/tetri6.txt
notval7:
	../fillit notvalid/tetri7.txt
notval8:
	../fillit notvalid/tetri8.txt
notval9:
	../fillit notvalid/tetri9.txt
notval10:
	../fillit notvalid/tetri10.txt
notval111:
	../fillit notvalid/tetri11.txt
notval12:
	../fillit notvalid/tetri12.txt
notval13:
	../fillit notvalid/tetri13.txt
notval14:
	../fillit notvalid/tetri14.txt
notval15:
	../fillit notvalid/tetri15.txt
notval16:
	../fillit notvalid/tetri16.txt
notval17:
	../fillit notvalid/tetri17.txt
notval18:
	../fillit notvalid/tetri18.txt
notval19:
	../fillit notvalid/tetri19.txt
notval20:
	../fillit notvalid/tetri20.txt
notval21:
	../fillit notvalid/tetri21.txt
notval22:
	../fillit notvalid/tetri22.txt
notval23:
	../fillit notvalid/tetri23.txt
notval24:
	../fillit notvalid/tetri24.txt
notval25:
	../fillit
